Company information component
armada-ths/ac22 pull request #15
Opened 2022-10-26 15:37 UTC by ninaayad

Updated version of the company information component

A dummy model was added that includes the modelling of a coordinator and extra information

2022-10-26 15:38 UTC, ninaayad commented
Asana task: https://app.asana.com/0/1203086797794980/1203239713536440/f

2022-10-27 19:21 UTC, yashdhanore requested changes
Hey! The design looks a lot like the figma design so good job! I left some comments that you can go over

2022-10-27 19:21 UTC, yashdhanore commented on src/App.tsx
> +import lunch_img from './assets/CompanyInformation/lunch-img.svg'
As @MehirWolde mention in one of the comments there are currently two different methods used for svg. [Here's how i did it](https://github.com/armada-ths/ac22/blob/0fd0c12d4d1e9a21f2b9c87f8d40675a37ade230/src/assets/InvalidEmail.tsx) so we need to decide one way to do it from next time. Since its already merged we can do it that way but if not then its fine we'll stick to this way.

2022-10-27 19:47 UTC, ninaayad commented on src/App.tsx
> +import lunch_img from './assets/CompanyInformation/lunch-img.svg'
Oh, okey, I'm not really familiar with SVGs so I just did it the easier way but I don't understand now, should I change it to how you did it or just keep it as is?

2022-10-27 19:55 UTC, ninaayad commented on src/components/CompanyInformation/CompanyInformation.css
> +  font-size: 0.75rem;
Great! Missed that, I just went with what I thought looked kind of similar but didn't look into the px size, I noticed now that pretty much all font-sizes are not the same as the design, so I will fix that. But would you recommend sticking to rem finding the same size or just change to px (seems like the easier way to do it)?

2022-10-27 21:24 UTC, yashdhanore commented on src/components/CompanyInformation/CompanyInformation.css
> +  font-size: 0.75rem;
I think it's better to use rem as most of our users won't be using the app on a laptop so the size should change according to the device size

2022-10-27 21:27 UTC, yashdhanore commented on src/App.tsx
> +import lunch_img from './assets/CompanyInformation/lunch-img.svg'
You can keep this one as it is now and for next time we can decide which way to use. 
I assume you used the same way in other PRs too? I haven't checked yet. If it's at a lot of places then we can stick to your way I have only used it once

2022-10-27 21:31 UTC, ninaayad commented on src/components/CompanyInformation/CompanyInformation.css
> +  font-size: 0.75rem;
Ok, I will get to it now then!

2022-10-27 21:34 UTC, ninaayad commented on src/App.tsx
> +import lunch_img from './assets/CompanyInformation/lunch-img.svg'
Yes, I've used this way for all of my components, but we could decide on it later and if you guys think it's better to do it the other way around I don't mind fixing it later on, I could fix it on my last PR which is the cpmpany page view, it's there that I use all these components.

2022-10-28 11:53 UTC, yashdhanore commented on src/components/CompanyInformation/CompanyInformation.css
> +  font-size: 0.75rem;
Looks better now! Especially the extra information section looks good!

2022-10-28 11:53 UTC, yashdhanore commented on src/App.tsx
> +import lunch_img from './assets/CompanyInformation/lunch-img.svg'
Sounds good! I'll merge this one for now then we can look into it

2022-10-28 11:57 UTC, yashdhanore approved these changes

2022-10-28 11:57 UTC, merged